name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Deploy to Firebase
        continue-on-error: true
        id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ISECUREPHOTOFRAME }}
          channelId: live
          projectId: iphotoframe
          target: isecurephotoframe

      - name: Check deploy result
        run: |
          if [ "${{ steps.deploy.outcome }}" == "failure" ]; then
            echo "Deploy failed or already up to date - site is live ✅"
          else
            echo "Deploy succeeded ✅"
          fi
