- name: Deploy to Firebase
  if: steps.changes.outputs.changed == 'true'
  uses: FirebaseExtended/action-hosting-deploy@v0
  with:
    repoToken: ${{ secrets.GITHUB_TOKEN }}
    firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ISECUREPHOTOFRAME }}
    channelId: live
    projectId: iphotoframe
    target: isecurephotoframe
